title: Blogging 101
author: ya boi
email: ya_boi@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn how to blog properly with ya boi
theme: minima
# social links
twitter_username: @ya_boi
github_username:  @ya_boi

show_excerpts: true # set to false to remove excerpts on the homepage
